<!--                                                             -*-html-*- -->
<li><a href="mailing_lists.html"
       >Mailing Lists</a></li>
<li><a href="planet/">Blogs</a></li>
<li><a href="meetings.html">Meetings</a></li>
<li><a href="irc://irc.freenode.net/ocaml">IRC</a></li>
<li><a href="http://stackoverflow.com/questions/tagged?tagnames=ocaml"
       >Stack Overflow</a></li>
<li><a href="http://www.reddit.com/r/ocaml/">Reddit</a></li>
<li><a href="support.html">Commercial Support</a></li>
