<!--                                                             -*-html-*- -->
<li><a href="releases/" >Releases</a></li>
<li><a href="libraries.html" >Libraries</a></li>
<li><a href="dev_tools.html" >Development Tools</a></li>
<li><a href="books.html#manual">User Manual</a></li>
<li><a href="cheat_sheets.html">Cheat Sheets</a></li>
<li><a href="http://search.ocaml.jp/" >OCaml API Search</a></li>
<li><a href="http://forge.ocamlcore.org/">Forge</a></li>
<li><a href="https://github.com/languages/OCaml"
       >GitHub</a></li>
<li><a href="https://bitbucket.org/repo/all?name=ocaml"
       >Bitbucket</a></li>
