<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <title>OCaml logos</title>
  </head>
  <body>
    <h1>OCaml logos</h1>

    <p>Web sites related to the OCaml language or that use it are
      encouraged to incorporate an OCaml logo somewhere in their page
      to indicate their support for OCaml development.  The logo
      should be linked to the OCaml website,
      <a href="http://ocaml.org/">http://ocaml.org/</a>.
    </p>

    <p>Several logos are available, you can choose the one you find the
      more appropriate for you. To include it on your web page, just copy
      and paste the associated HTML code. If you prefer, you can make a
      local copy of the image file on your web server.
    </p>

<table><tr><td style="text-align: right; vertical-align:middle; padding-right: 2em;">
<tr><td style="text-align: right; vertical-align:middle;
	       padding-right: 2em;"
	><img src="http://www.linux-nantes.org/~fmonnier/ocaml/ocaml.154x56.gif"
	      alt="OCaml"
	       /></td><td style="vertical-align:middle;"
><pre>
&lt;a href="http://ocaml.org"&gt;
  &lt;img src="http://www.linux-nantes.org/~fmonnier/ocaml/ocaml.154x56.gif"
       alt="OCaml"
       style="border: none;" /&gt;
&lt;/a&gt;</pre>
</td></tr>
<tr><td style="text-align: right; vertical-align:middle;
	       padding-right: 2em;"
	><img src="http://www.linux-nantes.org/~fmonnier/ocaml/powered-by-ocaml.152x58.gif"
	      alt="Powered by OCaml"
	       /></td><td style="vertical-align:middle;"
><pre>
&lt;a href="http://ocaml.org"&gt;
  &lt;img src="http://www.linux-nantes.org/~fmonnier/ocaml/powered-by-ocaml.152x58.gif"
       alt="Powered by OCaml"
       style="border: none;" /&gt;
&lt;/a&gt;</pre>
</td></tr>
<tr><td style="text-align: right; vertical-align:middle;
	       padding-right: 2em;"
	><img src="http://caml.inria.fr/pub/logos/generated-by-ocamldoc.190x58.gif"
	      alt="Generated by ocamldoc"
	       /></td><td style="vertical-align:middle;"
><pre>
&lt;a href="http://ocaml.org"&gt;
  &lt;img src="http://caml.inria.fr/pub/logos/generated-by-ocamldoc.190x58.gif"
       alt="Generated by ocamldoc"
       style="border: none;" /&gt;
&lt;/a&gt;</pre>
</td></tr>
<tr><td style="text-align: right; vertical-align:middle;
	       padding-right:
	       2em;"
	><img src="http://caml.inria.fr/pub/logos/generated-by-ocamldoc.80x30.gif"
	      alt="Generated by ocamldoc"
	      /></td><td style="vertical-align:middle;"
><pre>
&lt;a href="http://ocaml.org"&gt;
  &lt;img src="http://ocaml.org/pub/logos/generated-by-ocamldoc.80x30.gif"
       alt="Generated by ocamldoc" style="border: none;" /&gt;
&lt;/a&gt;</pre>
</td></tr>
<tr><td style="text-align: right;
	       vertical-align:middle; padding-right: 2em;"
	><img src="http://caml.inria.fr/pub/logos/ocamldoc.80x30.gif"
	      alt="ocamldoc"
	       /></td><td style="vertical-align:middle;"
><pre>
&lt;a href="http://ocaml.org"&gt;
  &lt;img src="http://caml.inria.fr/pub/logos/ocamldoc.80x30.gif"
      alt="ocamldoc"
      style="border: none;" /&gt;
&lt;/a&gt;</pre>
</td></tr></table>

  </body>
</html>
